# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adventures of a Software Engineer
description: Blog about Big Data and DevOps 
#email:
meta_description: >-
  Hey, my name is Phil. Although I work as a Big Data Software Engineer,
  I do a lot of DevOps stuff. Other topics, which will be covered on this blog,
  are Chat Bots, VR, and Blockchain.
long_description: >-
  Hey, my name is Phil. Although I work as a Big Data Software Engineer,
  I do a lot of DevOps stuff. Other topics, which will be covered on this blog,
  are Chat Bots, VR, and Blockchain.<br>Have you ever tried
  to setup a Hadoop cluster with SSL/TLS? Protip: don't do it! Sometimes, you're
  stuck on certain problems for hours or even days. And there isn't always a
  solution on StackOverflow or even on the whole internet. But in the end, you
  always gotta find a way to fix that problem. This is why I want to share with
  you my solutions to things that I come across on my daily work. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://philenius.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  philenius

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
timezone: Europe/Berlin

google_analytics: UA-80928743-3
just_comments: 7f6ffdfb-9d73-46c8-a469-324327e2abca
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
